# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20170604_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='presentation',
        ),
        migrations.AddField(
            model_name='presentation',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Paper'),
        ),
    ]
